import { HttpStatus } from '@nestjs/common';

import {
    CONFLICT_HTTP_PROBLEM,
    FORBIDDEN_HTTP_PROBLEM,
    INTERNAL_HTTP_PROBLEM,
    INVALID_REQUEST_HTTP_PROBLEM,
    NOT_FOUND_HTTP_PROBLEM,
    PAYLOAD_TOO_LARGE_HTTP_PROBLEM,
    SERVICE_UNAVAILABLE_HTTP_PROBLEM,
    TOO_MANY_REQUESTS_HTTP_PROBLEM,
    UNAUTHORIZED_HTTP_PROBLEM,
    UNPROCESSABLE_ENTITY_HTTP_PROBLEM,
    UNSUPPORTED_MEDIA_TYPE_HTTP_PROBLEM,
} from './http-problems.js';
import type { HttpProblemDefinition } from './problem-details.js';

const HTTP_STATUS_PROBLEMS: Readonly<Record<number, HttpProblemDefinition>> = Object.freeze({
    [HttpStatus.BAD_REQUEST]: INVALID_REQUEST_HTTP_PROBLEM,
    [HttpStatus.UNAUTHORIZED]: UNAUTHORIZED_HTTP_PROBLEM,
    [HttpStatus.FORBIDDEN]: FORBIDDEN_HTTP_PROBLEM,
    [HttpStatus.NOT_FOUND]: NOT_FOUND_HTTP_PROBLEM,
    [HttpStatus.CONFLICT]: CONFLICT_HTTP_PROBLEM,
    [HttpStatus.PAYLOAD_TOO_LARGE]: PAYLOAD_TOO_LARGE_HTTP_PROBLEM,
    [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: UNSUPPORTED_MEDIA_TYPE_HTTP_PROBLEM,
    [HttpStatus.UNPROCESSABLE_ENTITY]: UNPROCESSABLE_ENTITY_HTTP_PROBLEM,
    [HttpStatus.TOO_MANY_REQUESTS]: TOO_MANY_REQUESTS_HTTP_PROBLEM,
    [HttpStatus.SERVICE_UNAVAILABLE]: SERVICE_UNAVAILABLE_HTTP_PROBLEM,
});

export function mapHttpStatusToProblem(status: number): HttpProblemDefinition {
    return HTTP_STATUS_PROBLEMS[status] ?? INTERNAL_HTTP_PROBLEM;
}
